### ISSUE TITLE
Wrong information in description field

### ISSUE THREAD

**Issue by JJJ3434** [Lastaapps/hopitude_to_ical#1]
![image](https://github.com/Lastaapps/hopitude_to_ical/assets/63916210/b1588f9c-567e-499d-bbb2-a403f7d9191f)

when downloading the ical and importing it to google calendar the location and description fields are a bit mixed up

**Comment by Lastaapps** [comment]
Sure, I see, bug in refactoring/changing idea what to show, will be fixed soon, thanks.

**Comment by Lastaapps** [comment]
Should be fixed now
